/**
 * DriveMy — KPP1 Question Bank
 * Malaysian JPJ KPP1 Theory Exam Questions (Bilingual EN/BM)
 *
 * Categories: 'road-signs' | 'traffic-rules' | 'safety-principles'
 * Set IDs:    'quiz-pool' | 'mock-1' | 'mock-2' | 'mock-3'
 *
 * Sources: Based on official JPJ KPP1 syllabus, Malaysian Highway Code,
 * and established KPP1 question banks.
 * Content was rephrased for compliance with licensing restrictions.
 */

// ---------------------------------------------------------------------------
// QUIZ POOL — 60 questions (mix of all categories)
// ---------------------------------------------------------------------------
export const QUIZ_POOL = [
  // --- ROAD SIGNS (20 questions) ---
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 1,
    question_en: "What does a red circle with a white horizontal bar in the centre mean?",
    question_ms: "Apakah maksud bulatan merah dengan bar mendatar putih di tengah?",
    options_en: ["No entry", "Stop ahead", "Give way", "Speed limit"],
    options_ms: ["Dilarang masuk", "Berhenti di hadapan", "Beri laluan", "Had laju"],
    correct_index: 0,
    explanation_en: "A red circle with a white horizontal bar is the 'No Entry' sign. Vehicles must not enter the road or lane displaying this sign.",
    explanation_ms: "Bulatan merah dengan bar mendatar putih ialah tanda 'Dilarang Masuk'. Kenderaan tidak boleh memasuki jalan atau lorong yang mempamerkan tanda ini.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 2,
    question_en: "A triangular sign with a red border and an exclamation mark (!) indicates:",
    question_ms: "Tanda segitiga dengan sempadan merah dan tanda seru (!) menunjukkan:",
    options_en: ["General danger ahead", "Road works ahead", "Slippery road", "Steep hill"],
    options_ms: ["Bahaya am di hadapan", "Kerja jalan di hadapan", "Jalan licin", "Bukit curam"],
    correct_index: 0,
    explanation_en: "A triangular sign with a red border and exclamation mark warns of a general hazard ahead. Drivers should slow down and proceed with caution.",
    explanation_ms: "Tanda segitiga dengan sempadan merah dan tanda seru memberi amaran tentang bahaya am di hadapan. Pemandu harus memperlahankan kenderaan dan berhati-hati.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 3,
    question_en: "What shape are warning signs in Malaysia?",
    question_ms: "Apakah bentuk tanda amaran di Malaysia?",
    options_en: ["Triangle", "Circle", "Rectangle", "Diamond"],
    options_ms: ["Segitiga", "Bulatan", "Segi empat tepat", "Berlian"],
    correct_index: 0,
    explanation_en: "Warning signs in Malaysia are triangular in shape with a red border, alerting drivers to potential hazards ahead.",
    explanation_ms: "Tanda amaran di Malaysia berbentuk segitiga dengan sempadan merah, memberi amaran kepada pemandu tentang bahaya yang mungkin ada di hadapan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 4,
    question_en: "A blue circular sign with a white arrow pointing upward means:",
    question_ms: "Tanda bulatan biru dengan anak panah putih menghala ke atas bermaksud:",
    options_en: ["Go straight ahead only", "Turn right only", "Turn left only", "No U-turn"],
    options_ms: ["Pergi terus sahaja", "Belok kanan sahaja", "Belok kiri sahaja", "Dilarang pusing balik"],
    correct_index: 0,
    explanation_en: "A blue circular sign with a white upward arrow is a mandatory instruction sign meaning vehicles must go straight ahead only.",
    explanation_ms: "Tanda bulatan biru dengan anak panah putih ke atas ialah tanda arahan mandatori yang bermaksud kenderaan mesti pergi terus sahaja.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 5,
    question_en: "What does a red octagonal sign with the word 'STOP' mean?",
    question_ms: "Apakah maksud tanda oktagon merah dengan perkataan 'BERHENTI'?",
    options_en: ["Stop completely and give way to all traffic", "Slow down and proceed if clear", "Give way to oncoming traffic only", "Stop only if traffic is present"],
    options_ms: ["Berhenti sepenuhnya dan beri laluan kepada semua trafik", "Perlahan dan teruskan jika jalan kosong", "Beri laluan kepada trafik dari arah bertentangan sahaja", "Berhenti hanya jika ada trafik"],
    correct_index: 0,
    explanation_en: "The STOP sign requires drivers to come to a complete stop and give way to all traffic before proceeding. It is the only octagonal road sign.",
    explanation_ms: "Tanda BERHENTI memerlukan pemandu berhenti sepenuhnya dan memberi laluan kepada semua trafik sebelum meneruskan perjalanan. Ia adalah satu-satunya tanda jalan berbentuk oktagon.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 6,
    question_en: "A sign showing two arrows pointing in opposite directions on a single road indicates:",
    question_ms: "Tanda yang menunjukkan dua anak panah menghala ke arah bertentangan pada satu jalan menunjukkan:",
    options_en: ["Two-way traffic ahead", "One-way road ends", "Overtaking prohibited", "Road narrows"],
    options_ms: ["Trafik dua hala di hadapan", "Jalan sehala berakhir", "Dilarang memotong", "Jalan menyempit"],
    correct_index: 0,
    explanation_en: "Two opposing arrows on a single road sign warn that two-way traffic is ahead, meaning vehicles travel in both directions on the same road.",
    explanation_ms: "Dua anak panah bertentangan pada tanda jalan memberi amaran bahawa trafik dua hala ada di hadapan, bermakna kenderaan bergerak dalam kedua-dua arah pada jalan yang sama.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 7,
    question_en: "What does a yellow diamond-shaped sign with a black arrow bending to the right indicate?",
    question_ms: "Apakah maksud tanda berlian kuning dengan anak panah hitam membengkok ke kanan?",
    options_en: ["Curve ahead to the right", "Turn right compulsory", "Right lane closed", "Merge from right"],
    options_ms: ["Selekoh ke kanan di hadapan", "Wajib belok kanan", "Lorong kanan ditutup", "Cantum dari kanan"],
    correct_index: 0,
    explanation_en: "A yellow diamond sign with a bending arrow warns of a curve in the road ahead in the direction the arrow points.",
    explanation_ms: "Tanda berlian kuning dengan anak panah membengkok memberi amaran tentang selekoh jalan di hadapan mengikut arah anak panah.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 8,
    question_en: "A sign showing a pedestrian figure on a triangular background warns of:",
    question_ms: "Tanda yang menunjukkan figura pejalan kaki pada latar belakang segitiga memberi amaran tentang:",
    options_en: ["Pedestrian crossing ahead", "School zone", "Playground nearby", "Bus stop ahead"],
    options_ms: ["Lintasan pejalan kaki di hadapan", "Zon sekolah", "Taman permainan berdekatan", "Perhentian bas di hadapan"],
    correct_index: 0,
    explanation_en: "A triangular sign with a pedestrian figure warns drivers that a pedestrian crossing is ahead and they should be prepared to stop.",
    explanation_ms: "Tanda segitiga dengan figura pejalan kaki memberi amaran kepada pemandu bahawa lintasan pejalan kaki ada di hadapan dan mereka harus bersedia untuk berhenti.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 9,
    question_en: "What does a red circle with a number '60' inside mean?",
    question_ms: "Apakah maksud bulatan merah dengan nombor '60' di dalamnya?",
    options_en: ["Maximum speed limit is 60 km/h", "Minimum speed is 60 km/h", "Distance to next town is 60 km", "Road width is 60 metres"],
    options_ms: ["Had laju maksimum ialah 60 km/j", "Laju minimum ialah 60 km/j", "Jarak ke bandar seterusnya ialah 60 km", "Lebar jalan ialah 60 meter"],
    correct_index: 0,
    explanation_en: "A red circle with a number is a speed limit sign. The number indicates the maximum speed in km/h that vehicles may travel on that road.",
    explanation_ms: "Bulatan merah dengan nombor ialah tanda had laju. Nombor tersebut menunjukkan laju maksimum dalam km/j yang boleh dilalui kenderaan di jalan itu.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 10,
    question_en: "A sign with a red circle and a car with an 'X' through it means:",
    question_ms: "Tanda dengan bulatan merah dan kereta dengan 'X' melaluinya bermaksud:",
    options_en: ["No vehicles allowed", "No parking", "No stopping", "No overtaking"],
    options_ms: ["Tiada kenderaan dibenarkan", "Dilarang letak kereta", "Dilarang berhenti", "Dilarang memotong"],
    correct_index: 0,
    explanation_en: "A red circle with a crossed-out vehicle symbol prohibits all vehicles from using that road or area.",
    explanation_ms: "Bulatan merah dengan simbol kenderaan yang dipalang melarang semua kenderaan menggunakan jalan atau kawasan tersebut.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 11,
    question_en: "What colour are mandatory instruction signs in Malaysia?",
    question_ms: "Apakah warna tanda arahan mandatori di Malaysia?",
    options_en: ["Blue with white symbols", "Red with white symbols", "Yellow with black symbols", "Green with white symbols"],
    options_ms: ["Biru dengan simbol putih", "Merah dengan simbol putih", "Kuning dengan simbol hitam", "Hijau dengan simbol putih"],
    correct_index: 0,
    explanation_en: "Mandatory instruction signs in Malaysia are blue circles with white symbols. They tell drivers what they MUST do.",
    explanation_ms: "Tanda arahan mandatori di Malaysia ialah bulatan biru dengan simbol putih. Ia memberitahu pemandu apa yang MESTI mereka lakukan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 12,
    question_en: "A sign showing a truck on a slope with an arrow pointing downward warns of:",
    question_ms: "Tanda yang menunjukkan trak di cerun dengan anak panah menghala ke bawah memberi amaran tentang:",
    options_en: ["Steep downhill gradient ahead", "Steep uphill gradient ahead", "Truck parking area", "Heavy vehicle lane"],
    options_ms: ["Cerun menurun curam di hadapan", "Cerun menaik curam di hadapan", "Kawasan letak trak", "Lorong kenderaan berat"],
    correct_index: 0,
    explanation_en: "A truck on a downward slope warns of a steep downhill gradient ahead. Drivers should engage a lower gear and use engine braking.",
    explanation_ms: "Trak pada cerun menurun memberi amaran tentang cerun menurun curam di hadapan. Pemandu harus masukkan gear rendah dan gunakan brek enjin.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 13,
    question_en: "What does a 'Give Way' sign look like in Malaysia?",
    question_ms: "Bagaimanakah rupa tanda 'Beri Laluan' di Malaysia?",
    options_en: ["Inverted triangle with red border", "Red octagon", "Blue circle", "Yellow diamond"],
    options_ms: ["Segitiga terbalik dengan sempadan merah", "Oktagon merah", "Bulatan biru", "Berlian kuning"],
    correct_index: 0,
    explanation_en: "The Give Way sign is an inverted (upside-down) triangle with a red border. Drivers must yield to traffic on the major road.",
    explanation_ms: "Tanda Beri Laluan ialah segitiga terbalik dengan sempadan merah. Pemandu mesti memberi laluan kepada trafik di jalan utama.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 14,
    question_en: "A sign showing two cars side by side with a red cross through one means:",
    question_ms: "Tanda yang menunjukkan dua kereta bersebelahan dengan palang merah pada satu bermaksud:",
    options_en: ["No overtaking", "No parking", "No two-way traffic", "Lane closed"],
    options_ms: ["Dilarang memotong", "Dilarang letak kereta", "Tiada trafik dua hala", "Lorong ditutup"],
    correct_index: 0,
    explanation_en: "A no overtaking sign shows two vehicles side by side with a prohibition mark. Drivers must not overtake other vehicles in this zone.",
    explanation_ms: "Tanda dilarang memotong menunjukkan dua kenderaan bersebelahan dengan tanda larangan. Pemandu tidak boleh memotong kenderaan lain di zon ini.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 15,
    question_en: "What does a sign with a red circle and a 'P' crossed out mean?",
    question_ms: "Apakah maksud tanda dengan bulatan merah dan 'P' dipalang?",
    options_en: ["No parking", "No stopping", "No entry", "No U-turn"],
    options_ms: ["Dilarang letak kereta", "Dilarang berhenti", "Dilarang masuk", "Dilarang pusing balik"],
    correct_index: 0,
    explanation_en: "A red circle with a crossed-out 'P' means no parking. Vehicles must not be parked in this area at any time.",
    explanation_ms: "Bulatan merah dengan 'P' dipalang bermaksud dilarang letak kereta. Kenderaan tidak boleh diletakkan di kawasan ini pada bila-bila masa.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 16,
    question_en: "A sign showing a school bus and children indicates:",
    question_ms: "Tanda yang menunjukkan bas sekolah dan kanak-kanak menunjukkan:",
    options_en: ["School zone — drive slowly and carefully", "Bus stop ahead", "Children's playground", "School bus parking only"],
    options_ms: ["Zon sekolah — pandu perlahan dan berhati-hati", "Perhentian bas di hadapan", "Taman permainan kanak-kanak", "Letak kereta bas sekolah sahaja"],
    correct_index: 0,
    explanation_en: "A school zone sign warns drivers to reduce speed and be alert for children crossing or walking near the road.",
    explanation_ms: "Tanda zon sekolah memberi amaran kepada pemandu untuk mengurangkan laju dan berwaspada terhadap kanak-kanak yang menyeberang atau berjalan berhampiran jalan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 17,
    question_en: "What does a sign with wavy lines on a road surface indicate?",
    question_ms: "Apakah maksud tanda dengan garisan bergelombang pada permukaan jalan?",
    options_en: ["Slippery road surface", "Bumpy road", "Road works", "Flooded road"],
    options_ms: ["Permukaan jalan licin", "Jalan bergelombang", "Kerja jalan", "Jalan banjir"],
    correct_index: 0,
    explanation_en: "Wavy lines on a road surface sign warn of a slippery road ahead. Drivers should reduce speed and avoid sudden braking or steering.",
    explanation_ms: "Garisan bergelombang pada tanda permukaan jalan memberi amaran tentang jalan licin di hadapan. Pemandu harus mengurangkan laju dan elakkan brek atau stereng mengejut.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 18,
    question_en: "A green rectangular sign on a highway typically provides:",
    question_ms: "Tanda segi empat tepat hijau di lebuh raya biasanya memberikan:",
    options_en: ["Direction and distance information", "Speed limit information", "Warning of hazards", "Prohibition instructions"],
    options_ms: ["Maklumat arah dan jarak", "Maklumat had laju", "Amaran bahaya", "Arahan larangan"],
    correct_index: 0,
    explanation_en: "Green rectangular signs are informational signs used on highways to provide direction, distance, and destination information.",
    explanation_ms: "Tanda segi empat tepat hijau ialah tanda maklumat yang digunakan di lebuh raya untuk memberikan maklumat arah, jarak, dan destinasi.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 19,
    question_en: "What does a sign showing a car with skid marks beneath it warn of?",
    question_ms: "Apakah amaran tanda yang menunjukkan kereta dengan kesan gelincir di bawahnya?",
    options_en: ["Slippery road when wet", "Steep downhill", "Speed bump ahead", "Gravel road"],
    options_ms: ["Jalan licin ketika basah", "Cerun menurun curam", "Bonggol laju di hadapan", "Jalan berkerikil"],
    correct_index: 0,
    explanation_en: "A car with skid marks warns that the road surface becomes slippery when wet. Extra caution is needed in rainy conditions.",
    explanation_ms: "Kereta dengan kesan gelincir memberi amaran bahawa permukaan jalan menjadi licin ketika basah. Berhati-hati lebih diperlukan dalam keadaan hujan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "quiz-pool",
    order_index: 20,
    question_en: "A sign with a red circle and a 'U-turn' arrow crossed out means:",
    question_ms: "Tanda dengan bulatan merah dan anak panah 'pusing balik' dipalang bermaksud:",
    options_en: ["No U-turn allowed", "No left turn", "No right turn", "No turning at all"],
    options_ms: ["Dilarang pusing balik", "Dilarang belok kiri", "Dilarang belok kanan", "Dilarang membelok langsung"],
    correct_index: 0,
    explanation_en: "A no U-turn sign prohibits drivers from making a U-turn at that location. Violating this sign is an offence.",
    explanation_ms: "Tanda dilarang pusing balik melarang pemandu membuat pusingan U di lokasi tersebut. Melanggar tanda ini adalah satu kesalahan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  // --- TRAFFIC RULES (20 questions) ---
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 21,
    question_en: "What is the speed limit on a Malaysian expressway (highway) for cars?",
    question_ms: "Apakah had laju di lebuh raya Malaysia untuk kereta?",
    options_en: ["110 km/h", "90 km/h", "130 km/h", "100 km/h"],
    options_ms: ["110 km/j", "90 km/j", "130 km/j", "100 km/j"],
    correct_index: 0,
    explanation_en: "The maximum speed limit on Malaysian expressways for cars is 110 km/h unless otherwise indicated by signs.",
    explanation_ms: "Had laju maksimum di lebuh raya Malaysia untuk kereta ialah 110 km/j melainkan dinyatakan sebaliknya oleh tanda.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 22,
    question_en: "When must you use your headlights while driving in Malaysia?",
    question_ms: "Bilakah anda mesti menggunakan lampu hadapan semasa memandu di Malaysia?",
    options_en: ["Between sunset and sunrise, and when visibility is poor", "Only at night after 10 PM", "Only in tunnels", "Only when it is raining heavily"],
    options_ms: ["Antara matahari terbenam dan terbit, dan apabila penglihatan terhad", "Hanya pada waktu malam selepas pukul 10 malam", "Hanya dalam terowong", "Hanya ketika hujan lebat"],
    correct_index: 0,
    explanation_en: "Headlights must be used from sunset to sunrise and whenever visibility is reduced, such as in rain, fog, or smoke.",
    explanation_ms: "Lampu hadapan mesti digunakan dari matahari terbenam hingga terbit dan bila-bila masa penglihatan berkurangan, seperti dalam hujan, kabus, atau asap.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 23,
    question_en: "At a junction with no traffic lights or signs, who has the right of way?",
    question_ms: "Di persimpangan tanpa lampu isyarat atau tanda, siapa yang mempunyai keutamaan laluan?",
    options_en: ["Traffic on the major road", "The vehicle that arrives first", "Traffic coming from the right", "The larger vehicle"],
    options_ms: ["Trafik di jalan utama", "Kenderaan yang tiba dahulu", "Trafik dari sebelah kanan", "Kenderaan yang lebih besar"],
    correct_index: 0,
    explanation_en: "At an unmarked junction, traffic on the major road has right of way. Vehicles entering from a minor road must give way.",
    explanation_ms: "Di persimpangan tanpa tanda, trafik di jalan utama mempunyai keutamaan laluan. Kenderaan yang memasuki dari jalan kecil mesti memberi laluan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 24,
    question_en: "What should you do when you hear an emergency vehicle siren behind you?",
    question_ms: "Apakah yang perlu anda lakukan apabila mendengar siren kenderaan kecemasan di belakang anda?",
    options_en: ["Move to the left and stop if necessary to let it pass", "Speed up to get out of the way", "Stop immediately in your lane", "Flash your hazard lights and continue"],
    options_ms: ["Bergerak ke kiri dan berhenti jika perlu untuk membiarkannya lalu", "Percepatkan untuk mengelak", "Berhenti serta-merta di lorong anda", "Nyalakan lampu amaran dan teruskan"],
    correct_index: 0,
    explanation_en: "When an emergency vehicle approaches with its siren on, you must move to the left side of the road and stop if necessary to allow it to pass safely.",
    explanation_ms: "Apabila kenderaan kecemasan menghampiri dengan siren berbunyi, anda mesti bergerak ke sebelah kiri jalan dan berhenti jika perlu untuk membolehkannya lalu dengan selamat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 25,
    question_en: "What is the minimum following distance recommended on a highway at 90 km/h?",
    question_ms: "Apakah jarak mengekori minimum yang disyorkan di lebuh raya pada 90 km/j?",
    options_en: ["At least 2 seconds gap (safe following distance)", "1 car length", "5 metres", "10 metres"],
    options_ms: ["Sekurang-kurangnya jurang 2 saat (jarak mengekori selamat)", "1 panjang kereta", "5 meter", "10 meter"],
    correct_index: 0,
    explanation_en: "The 2-second rule is the minimum safe following distance. At higher speeds, a 3-4 second gap is recommended for safety.",
    explanation_ms: "Peraturan 2 saat ialah jarak mengekori selamat minimum. Pada laju yang lebih tinggi, jurang 3-4 saat disyorkan untuk keselamatan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 26,
    question_en: "When is it legal to use the emergency lane on a Malaysian highway?",
    question_ms: "Bilakah dibenarkan menggunakan lorong kecemasan di lebuh raya Malaysia?",
    options_en: ["Only in a genuine emergency or vehicle breakdown", "During peak hours to avoid traffic", "When the main lanes are congested", "Motorcycles may use it at any time"],
    options_ms: ["Hanya dalam kecemasan sebenar atau kerosakan kenderaan", "Semasa waktu puncak untuk mengelak trafik", "Apabila lorong utama sesak", "Motosikal boleh menggunakannya pada bila-bila masa"],
    correct_index: 0,
    explanation_en: "The emergency lane is reserved for genuine emergencies and vehicle breakdowns only. Using it otherwise is illegal and dangerous.",
    explanation_ms: "Lorong kecemasan dikhaskan untuk kecemasan sebenar dan kerosakan kenderaan sahaja. Menggunakannya selain itu adalah haram dan berbahaya.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 27,
    question_en: "What does a solid white line in the centre of the road mean?",
    question_ms: "Apakah maksud garisan putih pepejal di tengah jalan?",
    options_en: ["No overtaking — do not cross the line", "Lane boundary only", "Pedestrian crossing zone", "Parking permitted on the right"],
    options_ms: ["Dilarang memotong — jangan melintas garisan", "Sempadan lorong sahaja", "Zon lintasan pejalan kaki", "Letak kereta dibenarkan di sebelah kanan"],
    correct_index: 0,
    explanation_en: "A solid white centre line means overtaking is prohibited. Drivers must not cross or straddle this line.",
    explanation_ms: "Garisan putih pepejal di tengah bermaksud memotong dilarang. Pemandu tidak boleh melintas atau menunggang garisan ini.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 28,
    question_en: "How far before a junction must you signal your intention to turn?",
    question_ms: "Berapa jauh sebelum persimpangan anda mesti memberi isyarat niat untuk membelok?",
    options_en: ["At least 30 metres before the junction", "Just before turning", "10 metres before", "50 metres before on highways only"],
    options_ms: ["Sekurang-kurangnya 30 meter sebelum persimpangan", "Sebaik sahaja sebelum membelok", "10 meter sebelum", "50 meter sebelum di lebuh raya sahaja"],
    correct_index: 0,
    explanation_en: "Drivers must signal at least 30 metres before a junction to give other road users adequate warning of their intention to turn.",
    explanation_ms: "Pemandu mesti memberi isyarat sekurang-kurangnya 30 meter sebelum persimpangan untuk memberi amaran yang mencukupi kepada pengguna jalan lain tentang niat mereka untuk membelok.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 29,
    question_en: "What is the blood alcohol concentration (BAC) legal limit for drivers in Malaysia?",
    question_ms: "Apakah had kepekatan alkohol dalam darah (BAC) yang sah untuk pemandu di Malaysia?",
    options_en: ["0.08% (80 mg per 100 ml of blood)", "0.05% (50 mg per 100 ml of blood)", "0.10% (100 mg per 100 ml of blood)", "Zero tolerance — no alcohol at all"],
    options_ms: ["0.08% (80 mg per 100 ml darah)", "0.05% (50 mg per 100 ml darah)", "0.10% (100 mg per 100 ml darah)", "Sifar toleransi — tiada alkohol langsung"],
    correct_index: 0,
    explanation_en: "The legal BAC limit in Malaysia is 80 mg of alcohol per 100 ml of blood (0.08%). Exceeding this is a criminal offence.",
    explanation_ms: "Had BAC yang sah di Malaysia ialah 80 mg alkohol per 100 ml darah (0.08%). Melebihi had ini adalah kesalahan jenayah.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 30,
    question_en: "When approaching a zebra crossing with a pedestrian waiting, you must:",
    question_ms: "Apabila menghampiri lintasan zebra dengan pejalan kaki menunggu, anda mesti:",
    options_en: ["Stop and allow the pedestrian to cross", "Sound your horn and proceed", "Slow down but continue if the pedestrian is not yet on the crossing", "Flash your headlights to warn the pedestrian"],
    options_ms: ["Berhenti dan benarkan pejalan kaki menyeberang", "Bunyikan hon dan teruskan", "Perlahan tetapi teruskan jika pejalan kaki belum di lintasan", "Kelipkan lampu hadapan untuk memberi amaran kepada pejalan kaki"],
    correct_index: 0,
    explanation_en: "At a zebra crossing, drivers must stop and give way to any pedestrian waiting to cross or already crossing.",
    explanation_ms: "Di lintasan zebra, pemandu mesti berhenti dan memberi laluan kepada mana-mana pejalan kaki yang menunggu untuk menyeberang atau sedang menyeberang.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 31,
    question_en: "What does a flashing amber traffic light mean?",
    question_ms: "Apakah maksud lampu isyarat lalu lintas kuning berkelip?",
    options_en: ["Proceed with caution", "Stop if safe to do so", "Prepare to stop", "Road closed ahead"],
    options_ms: ["Teruskan dengan berhati-hati", "Berhenti jika selamat berbuat demikian", "Bersedia untuk berhenti", "Jalan ditutup di hadapan"],
    correct_index: 0,
    explanation_en: "A flashing amber light means proceed with caution. Drivers should slow down and be alert for hazards.",
    explanation_ms: "Lampu kuning berkelip bermaksud teruskan dengan berhati-hati. Pemandu harus memperlahankan kenderaan dan berwaspada terhadap bahaya.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 32,
    question_en: "On a two-lane road, when is it safe to overtake?",
    question_ms: "Di jalan dua lorong, bilakah selamat untuk memotong?",
    options_en: ["When the road ahead is clear and there is a broken centre line", "Whenever you want to go faster", "On bends and hills", "When the vehicle ahead is slow"],
    options_ms: ["Apabila jalan di hadapan kosong dan ada garisan tengah putus-putus", "Bila-bila masa anda ingin pergi lebih laju", "Di selekoh dan bukit", "Apabila kenderaan di hadapan perlahan"],
    correct_index: 0,
    explanation_en: "Overtaking is only safe when the road ahead is clearly visible, there is a broken centre line, and there is sufficient space and time to complete the manoeuvre.",
    explanation_ms: "Memotong hanya selamat apabila jalan di hadapan jelas kelihatan, ada garisan tengah putus-putus, dan ada ruang dan masa yang mencukupi untuk melengkapkan manuver.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 33,
    question_en: "What is the speed limit in a school zone in Malaysia?",
    question_ms: "Apakah had laju di zon sekolah di Malaysia?",
    options_en: ["30 km/h", "40 km/h", "50 km/h", "60 km/h"],
    options_ms: ["30 km/j", "40 km/j", "50 km/j", "60 km/j"],
    correct_index: 0,
    explanation_en: "The speed limit in a school zone is 30 km/h to protect children. This applies during school hours and when children are present.",
    explanation_ms: "Had laju di zon sekolah ialah 30 km/j untuk melindungi kanak-kanak. Ini terpakai semasa waktu sekolah dan apabila kanak-kanak hadir.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 34,
    question_en: "When parking on a hill facing downhill, which way should you turn your front wheels?",
    question_ms: "Apabila meletak kereta di bukit menghadap ke bawah, ke arah manakah anda harus memusingkan roda hadapan?",
    options_en: ["Toward the kerb (right if no kerb)", "Away from the kerb", "Straight ahead", "It does not matter"],
    options_ms: ["Ke arah kerb (kanan jika tiada kerb)", "Menjauhi kerb", "Terus ke hadapan", "Tidak kira"],
    correct_index: 0,
    explanation_en: "When parking facing downhill, turn wheels toward the kerb so the vehicle rolls into the kerb if the brakes fail, preventing it from rolling into traffic.",
    explanation_ms: "Apabila meletak kereta menghadap ke bawah bukit, pusingkan roda ke arah kerb supaya kenderaan bergolek ke kerb jika brek gagal, menghalangnya daripada bergolek ke dalam trafik.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 35,
    question_en: "What must you do before changing lanes on a highway?",
    question_ms: "Apakah yang mesti anda lakukan sebelum menukar lorong di lebuh raya?",
    options_en: ["Check mirrors, signal, check blind spot, then move", "Just signal and move", "Check mirrors only", "Sound horn and move"],
    options_ms: ["Periksa cermin, beri isyarat, periksa titik buta, kemudian bergerak", "Hanya beri isyarat dan bergerak", "Periksa cermin sahaja", "Bunyikan hon dan bergerak"],
    correct_index: 0,
    explanation_en: "The safe lane-change procedure is: check mirrors, signal your intention, check the blind spot by looking over your shoulder, then move if safe.",
    explanation_ms: "Prosedur tukar lorong yang selamat ialah: periksa cermin, beri isyarat niat anda, periksa titik buta dengan melihat ke belakang bahu, kemudian bergerak jika selamat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 36,
    question_en: "What is the maximum speed limit on a Malaysian federal road (non-highway)?",
    question_ms: "Apakah had laju maksimum di jalan persekutuan Malaysia (bukan lebuh raya)?",
    options_en: ["90 km/h", "110 km/h", "70 km/h", "80 km/h"],
    options_ms: ["90 km/j", "110 km/j", "70 km/j", "80 km/j"],
    correct_index: 0,
    explanation_en: "The maximum speed limit on Malaysian federal roads (non-expressways) is 90 km/h for cars unless otherwise posted.",
    explanation_ms: "Had laju maksimum di jalan persekutuan Malaysia (bukan lebuh raya) ialah 90 km/j untuk kereta melainkan dinyatakan sebaliknya.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 37,
    question_en: "When must you NOT use your horn?",
    question_ms: "Bilakah anda TIDAK BOLEH menggunakan hon?",
    options_en: ["In a hospital zone or quiet area at night", "When a pedestrian is crossing", "When another vehicle cuts in front of you", "When approaching a blind bend"],
    options_ms: ["Di zon hospital atau kawasan sunyi pada waktu malam", "Apabila pejalan kaki menyeberang", "Apabila kenderaan lain memotong di hadapan anda", "Apabila menghampiri selekoh buta"],
    correct_index: 0,
    explanation_en: "Using a horn in hospital zones or quiet residential areas at night is prohibited as it causes unnecessary noise disturbance.",
    explanation_ms: "Menggunakan hon di zon hospital atau kawasan kediaman sunyi pada waktu malam adalah dilarang kerana ia menyebabkan gangguan bunyi yang tidak perlu.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 38,
    question_en: "What does a double yellow line at the edge of the road mean?",
    question_ms: "Apakah maksud garisan kuning berganda di tepi jalan?",
    options_en: ["No parking or stopping at any time", "No parking during peak hours only", "Parking permitted for 30 minutes", "Loading and unloading only"],
    options_ms: ["Dilarang letak kereta atau berhenti pada bila-bila masa", "Dilarang letak kereta semasa waktu puncak sahaja", "Letak kereta dibenarkan selama 30 minit", "Memuat dan memunggah sahaja"],
    correct_index: 0,
    explanation_en: "A double yellow line means no parking or stopping is permitted at any time. This is stricter than a single yellow line.",
    explanation_ms: "Garisan kuning berganda bermaksud tiada letak kereta atau berhenti dibenarkan pada bila-bila masa. Ini lebih ketat daripada garisan kuning tunggal.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 39,
    question_en: "What is the correct action when a school bus has stopped and its amber lights are flashing?",
    question_ms: "Apakah tindakan yang betul apabila bas sekolah telah berhenti dan lampu ambernya berkelip?",
    options_en: ["Stop and wait until children have safely boarded or alighted", "Slow down and pass carefully", "Sound horn to warn children", "Use the opposite lane to pass quickly"],
    options_ms: ["Berhenti dan tunggu sehingga kanak-kanak telah menaiki atau turun dengan selamat", "Perlahan dan lalu dengan berhati-hati", "Bunyikan hon untuk memberi amaran kepada kanak-kanak", "Gunakan lorong bertentangan untuk lalu dengan cepat"],
    correct_index: 0,
    explanation_en: "When a school bus stops with flashing amber lights, all traffic must stop and wait until children have safely boarded or alighted and the bus moves on.",
    explanation_ms: "Apabila bas sekolah berhenti dengan lampu amber berkelip, semua trafik mesti berhenti dan menunggu sehingga kanak-kanak telah menaiki atau turun dengan selamat dan bas bergerak.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "quiz-pool",
    order_index: 40,
    question_en: "What is the minimum age to apply for a Malaysian car driving licence (Class D)?",
    question_ms: "Apakah umur minimum untuk memohon lesen memandu kereta Malaysia (Kelas D)?",
    options_en: ["17 years old", "16 years old", "18 years old", "21 years old"],
    options_ms: ["17 tahun", "16 tahun", "18 tahun", "21 tahun"],
    correct_index: 0,
    explanation_en: "The minimum age to apply for a Malaysian Class D (car) driving licence is 17 years old.",
    explanation_ms: "Umur minimum untuk memohon lesen memandu Kelas D (kereta) Malaysia ialah 17 tahun.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  // --- SAFETY PRINCIPLES (20 questions) ---
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 41,
    question_en: "What is the primary cause of road accidents in Malaysia?",
    question_ms: "Apakah punca utama kemalangan jalan raya di Malaysia?",
    options_en: ["Human error (speeding, distraction, fatigue)", "Poor road conditions", "Vehicle defects", "Bad weather"],
    options_ms: ["Kesilapan manusia (memandu laju, gangguan, keletihan)", "Keadaan jalan yang buruk", "Kecacatan kenderaan", "Cuaca buruk"],
    correct_index: 0,
    explanation_en: "Human error, including speeding, distracted driving, and driver fatigue, is the primary cause of road accidents in Malaysia.",
    explanation_ms: "Kesilapan manusia, termasuk memandu laju, memandu sambil terganggu, dan keletihan pemandu, adalah punca utama kemalangan jalan raya di Malaysia.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 42,
    question_en: "How should you check your tyre pressure?",
    question_ms: "Bagaimanakah anda harus memeriksa tekanan tayar?",
    options_en: ["When tyres are cold, before driving", "After a long drive when tyres are warm", "Only when the tyre looks flat", "Once a year during service"],
    options_ms: ["Apabila tayar sejuk, sebelum memandu", "Selepas perjalanan jauh apabila tayar panas", "Hanya apabila tayar kelihatan kempes", "Sekali setahun semasa servis"],
    correct_index: 0,
    explanation_en: "Tyre pressure should be checked when tyres are cold (before driving or after the vehicle has been stationary for at least 3 hours) for an accurate reading.",
    explanation_ms: "Tekanan tayar harus diperiksa apabila tayar sejuk (sebelum memandu atau selepas kenderaan pegun sekurang-kurangnya 3 jam) untuk bacaan yang tepat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 43,
    question_en: "What should you do if your vehicle's brakes fail while driving?",
    question_ms: "Apakah yang perlu anda lakukan jika brek kenderaan anda gagal semasa memandu?",
    options_en: ["Pump the brakes, downshift gears, use handbrake gradually, steer to safety", "Immediately apply the handbrake fully", "Turn off the engine", "Open the door and jump out"],
    options_ms: ["Pam brek, turunkan gear, gunakan brek tangan secara beransur, stereng ke tempat selamat", "Segera gunakan brek tangan sepenuhnya", "Matikan enjin", "Buka pintu dan lompat keluar"],
    correct_index: 0,
    explanation_en: "If brakes fail: pump the brake pedal to build pressure, downshift to lower gears to slow down, apply the handbrake gradually, and steer toward a safe area.",
    explanation_ms: "Jika brek gagal: pam pedal brek untuk membina tekanan, turunkan ke gear rendah untuk memperlahankan, gunakan brek tangan secara beransur, dan stereng ke kawasan selamat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 44,
    question_en: "What is the correct way to wear a seatbelt?",
    question_ms: "Apakah cara yang betul untuk memakai tali pinggang keledar?",
    options_en: ["Lap belt across hips, shoulder belt across chest and shoulder", "Shoulder belt only, tucked under the arm", "Lap belt only", "Loosely across the body"],
    options_ms: ["Tali pinggang merentasi pinggul, tali bahu merentasi dada dan bahu", "Tali bahu sahaja, diselitkan di bawah lengan", "Tali pinggang sahaja", "Longgar merentasi badan"],
    correct_index: 0,
    explanation_en: "A seatbelt must be worn with the lap belt across the hips (not the stomach) and the shoulder belt across the chest and shoulder, not tucked under the arm.",
    explanation_ms: "Tali pinggang keledar mesti dipakai dengan tali pinggang merentasi pinggul (bukan perut) dan tali bahu merentasi dada dan bahu, tidak diselitkan di bawah lengan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 45,
    question_en: "What is aquaplaning (hydroplaning)?",
    question_ms: "Apakah aquaplaning (hydroplaning)?",
    options_en: ["When tyres lose contact with the road due to a layer of water", "When the engine overheats in rain", "When windscreen wipers fail", "When brakes lock up on wet roads"],
    options_ms: ["Apabila tayar kehilangan hubungan dengan jalan akibat lapisan air", "Apabila enjin terlalu panas dalam hujan", "Apabila pengelap cermin depan gagal", "Apabila brek terkunci di jalan basah"],
    correct_index: 0,
    explanation_en: "Aquaplaning occurs when a layer of water builds up between the tyres and road surface, causing the vehicle to lose traction and steering control.",
    explanation_ms: "Aquaplaning berlaku apabila lapisan air terbina antara tayar dan permukaan jalan, menyebabkan kenderaan kehilangan daya cengkaman dan kawalan stereng.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 46,
    question_en: "How often should engine oil be checked?",
    question_ms: "Berapa kerap minyak enjin harus diperiksa?",
    options_en: ["Before every long journey and at least monthly", "Only during annual service", "Every 6 months", "Only when the oil warning light comes on"],
    options_ms: ["Sebelum setiap perjalanan jauh dan sekurang-kurangnya setiap bulan", "Hanya semasa servis tahunan", "Setiap 6 bulan", "Hanya apabila lampu amaran minyak menyala"],
    correct_index: 0,
    explanation_en: "Engine oil should be checked before every long journey and at least once a month. Low oil can cause serious engine damage.",
    explanation_ms: "Minyak enjin harus diperiksa sebelum setiap perjalanan jauh dan sekurang-kurangnya sekali sebulan. Minyak yang rendah boleh menyebabkan kerosakan enjin yang serius.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 47,
    question_en: "What should you do if you feel drowsy while driving on a highway?",
    question_ms: "Apakah yang perlu anda lakukan jika anda berasa mengantuk semasa memandu di lebuh raya?",
    options_en: ["Pull over at the nearest rest area and take a short nap", "Open the window and turn up the radio", "Drink coffee and continue driving", "Drive faster to reach your destination sooner"],
    options_ms: ["Berhenti di kawasan rehat terdekat dan tidur sebentar", "Buka tingkap dan naikkan radio", "Minum kopi dan teruskan memandu", "Pandu lebih laju untuk sampai ke destinasi lebih cepat"],
    correct_index: 0,
    explanation_en: "If drowsy, the only safe action is to pull over at a rest area and sleep for at least 20 minutes. Drowsy driving is as dangerous as drunk driving.",
    explanation_ms: "Jika mengantuk, satu-satunya tindakan selamat ialah berhenti di kawasan rehat dan tidur sekurang-kurangnya 20 minit. Memandu mengantuk sama berbahayanya dengan memandu mabuk.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 48,
    question_en: "What is the correct child car seat position for a baby under 1 year old?",
    question_ms: "Apakah kedudukan tempat duduk kereta kanak-kanak yang betul untuk bayi bawah 1 tahun?",
    options_en: ["Rear-facing in the back seat", "Forward-facing in the front seat", "Rear-facing in the front seat", "Forward-facing in the back seat"],
    options_ms: ["Menghadap ke belakang di tempat duduk belakang", "Menghadap ke hadapan di tempat duduk hadapan", "Menghadap ke belakang di tempat duduk hadapan", "Menghadap ke hadapan di tempat duduk belakang"],
    correct_index: 0,
    explanation_en: "Babies under 1 year must be in a rear-facing car seat in the back seat. This position best protects the head, neck, and spine in a crash.",
    explanation_ms: "Bayi bawah 1 tahun mesti berada dalam tempat duduk kereta menghadap ke belakang di tempat duduk belakang. Kedudukan ini paling baik melindungi kepala, leher, dan tulang belakang dalam kemalangan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 49,
    question_en: "What should you do immediately after a minor road accident with no injuries?",
    question_ms: "Apakah yang perlu anda lakukan serta-merta selepas kemalangan jalan raya kecil tanpa kecederaan?",
    options_en: ["Move vehicles to the side, exchange details, report to police within 24 hours", "Leave the scene immediately", "Argue with the other driver about fault", "Wait in the middle of the road"],
    options_ms: ["Pindahkan kenderaan ke tepi, tukar maklumat, lapor kepada polis dalam masa 24 jam", "Tinggalkan tempat kejadian serta-merta", "Berdebat dengan pemandu lain tentang kesalahan", "Tunggu di tengah jalan"],
    correct_index: 0,
    explanation_en: "After a minor accident: move vehicles off the road if possible, exchange names, IC numbers, and insurance details, then report to the nearest police station within 24 hours.",
    explanation_ms: "Selepas kemalangan kecil: pindahkan kenderaan dari jalan jika boleh, tukar nama, nombor IC, dan maklumat insurans, kemudian lapor ke balai polis terdekat dalam masa 24 jam.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 50,
    question_en: "What is the purpose of the tread depth on a tyre?",
    question_ms: "Apakah tujuan kedalaman alur pada tayar?",
    options_en: ["To channel water away and maintain grip on wet roads", "To make the tyre look new", "To reduce tyre noise", "To improve fuel economy"],
    options_ms: ["Untuk mengalirkan air dan mengekalkan cengkaman di jalan basah", "Untuk menjadikan tayar kelihatan baru", "Untuk mengurangkan bunyi tayar", "Untuk meningkatkan ekonomi bahan api"],
    correct_index: 0,
    explanation_en: "Tyre tread channels water away from the contact patch, maintaining grip on wet roads. The minimum legal tread depth in Malaysia is 1.6 mm.",
    explanation_ms: "Alur tayar mengalirkan air dari kawasan sentuhan, mengekalkan cengkaman di jalan basah. Kedalaman alur minimum yang sah di Malaysia ialah 1.6 mm.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 51,
    question_en: "What does the term 'defensive driving' mean?",
    question_ms: "Apakah maksud istilah 'memandu defensif'?",
    options_en: ["Anticipating hazards and driving to avoid accidents caused by others", "Driving slowly at all times", "Staying in the left lane always", "Avoiding highways"],
    options_ms: ["Menjangka bahaya dan memandu untuk mengelak kemalangan yang disebabkan oleh orang lain", "Memandu perlahan pada setiap masa", "Sentiasa berada di lorong kiri", "Mengelak lebuh raya"],
    correct_index: 0,
    explanation_en: "Defensive driving means anticipating potential hazards, maintaining awareness of other road users, and taking proactive steps to avoid accidents.",
    explanation_ms: "Memandu defensif bermaksud menjangka bahaya yang berpotensi, mengekalkan kesedaran tentang pengguna jalan lain, dan mengambil langkah proaktif untuk mengelak kemalangan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 52,
    question_en: "What is the effect of using a mobile phone while driving?",
    question_ms: "Apakah kesan menggunakan telefon bimbit semasa memandu?",
    options_en: ["Significantly increases reaction time and risk of accident", "Has no effect if using hands-free", "Only dangerous at high speeds", "Acceptable for short calls"],
    options_ms: ["Meningkatkan masa tindak balas dan risiko kemalangan dengan ketara", "Tidak ada kesan jika menggunakan hands-free", "Hanya berbahaya pada laju tinggi", "Boleh diterima untuk panggilan pendek"],
    correct_index: 0,
    explanation_en: "Using a mobile phone while driving — even hands-free — significantly increases reaction time and the risk of an accident. It is illegal to hold a phone while driving in Malaysia.",
    explanation_ms: "Menggunakan telefon bimbit semasa memandu — walaupun hands-free — meningkatkan masa tindak balas dan risiko kemalangan dengan ketara. Adalah haram untuk memegang telefon semasa memandu di Malaysia.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 53,
    question_en: "What should you check before starting a long journey?",
    question_ms: "Apakah yang perlu anda periksa sebelum memulakan perjalanan jauh?",
    options_en: ["Tyres, engine oil, water, brakes, lights, and fuel", "Fuel only", "Tyres and fuel only", "Engine oil and fuel only"],
    options_ms: ["Tayar, minyak enjin, air, brek, lampu, dan bahan api", "Bahan api sahaja", "Tayar dan bahan api sahaja", "Minyak enjin dan bahan api sahaja"],
    correct_index: 0,
    explanation_en: "Before a long journey, always check: tyre pressure and condition, engine oil level, coolant level, brake fluid, all lights, and fuel level.",
    explanation_ms: "Sebelum perjalanan jauh, sentiasa periksa: tekanan dan keadaan tayar, paras minyak enjin, paras cecair penyejuk, cecair brek, semua lampu, dan paras bahan api.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 54,
    question_en: "What is the correct action if your vehicle starts to skid?",
    question_ms: "Apakah tindakan yang betul jika kenderaan anda mula gelincir?",
    options_en: ["Steer in the direction of the skid and ease off the accelerator", "Brake hard immediately", "Steer in the opposite direction of the skid", "Accelerate to regain control"],
    options_ms: ["Stereng ke arah gelinciran dan kurangkan tekanan pada pemecut", "Brek keras serta-merta", "Stereng ke arah bertentangan dengan gelinciran", "Pecutkan untuk mendapatkan semula kawalan"],
    correct_index: 0,
    explanation_en: "When skidding, steer in the direction the rear of the car is sliding (into the skid) and ease off the accelerator. Do not brake suddenly as this worsens the skid.",
    explanation_ms: "Apabila gelincir, stereng ke arah bahagian belakang kereta meluncur (ke arah gelinciran) dan kurangkan tekanan pada pemecut. Jangan brek mengejut kerana ini memburukkan gelinciran.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 55,
    question_en: "What is the stopping distance at 60 km/h on a dry road?",
    question_ms: "Apakah jarak berhenti pada 60 km/j di jalan kering?",
    options_en: ["Approximately 36 metres (thinking + braking distance)", "10 metres", "20 metres", "50 metres"],
    options_ms: ["Lebih kurang 36 meter (jarak berfikir + jarak brek)", "10 meter", "20 meter", "50 meter"],
    correct_index: 0,
    explanation_en: "At 60 km/h on a dry road, the total stopping distance is approximately 36 metres: about 15 m thinking distance plus 21 m braking distance.",
    explanation_ms: "Pada 60 km/j di jalan kering, jumlah jarak berhenti adalah lebih kurang 36 meter: lebih kurang 15 m jarak berfikir ditambah 21 m jarak brek.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 56,
    question_en: "What does the 'POWDERS' pre-drive check stand for?",
    question_ms: "Apakah maksud pemeriksaan pra-pemanduan 'POWDERS'?",
    options_en: ["Petrol, Oil, Water, Damage, Electrics, Rubber, Safety", "Pressure, Oil, Wipers, Doors, Engine, Radio, Seatbelt", "Petrol, Oil, Windows, Dashboard, Engine, Rubber, Steering", "None of the above — it is not a standard check"],
    options_ms: ["Petrol, Minyak, Air, Kerosakan, Elektrik, Getah, Keselamatan", "Tekanan, Minyak, Pengelap, Pintu, Enjin, Radio, Tali pinggang", "Petrol, Minyak, Tingkap, Papan pemuka, Enjin, Getah, Stereng", "Tiada di atas — ia bukan pemeriksaan standard"],
    correct_index: 0,
    explanation_en: "POWDERS is a pre-drive safety check: Petrol (fuel), Oil (engine oil), Water (coolant), Damage (body damage), Electrics (lights/battery), Rubber (tyres), Safety (seatbelts/mirrors).",
    explanation_ms: "POWDERS ialah pemeriksaan keselamatan pra-pemanduan: Petrol (bahan api), Oil (minyak enjin), Water (cecair penyejuk), Damage (kerosakan badan), Electrics (lampu/bateri), Rubber (tayar), Safety (tali pinggang/cermin).",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 57,
    question_en: "What is the safest way to drive in heavy rain?",
    question_ms: "Apakah cara paling selamat untuk memandu dalam hujan lebat?",
    options_en: ["Reduce speed, increase following distance, use headlights, avoid sudden braking", "Maintain normal speed to get through the rain faster", "Use hazard lights and drive in the middle of the road", "Stop immediately on the road"],
    options_ms: ["Kurangkan laju, tingkatkan jarak mengekori, gunakan lampu hadapan, elakkan brek mengejut", "Kekalkan laju biasa untuk melalui hujan lebih cepat", "Gunakan lampu amaran dan pandu di tengah jalan", "Berhenti serta-merta di jalan"],
    correct_index: 0,
    explanation_en: "In heavy rain: reduce speed significantly, increase following distance to at least 4 seconds, turn on headlights, and avoid sudden braking to prevent skidding.",
    explanation_ms: "Dalam hujan lebat: kurangkan laju dengan ketara, tingkatkan jarak mengekori kepada sekurang-kurangnya 4 saat, hidupkan lampu hadapan, dan elakkan brek mengejut untuk mencegah gelinciran.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 58,
    question_en: "What should you do if your engine catches fire while driving?",
    question_ms: "Apakah yang perlu anda lakukan jika enjin anda terbakar semasa memandu?",
    options_en: ["Pull over safely, turn off engine, evacuate all passengers, call emergency services", "Open the bonnet immediately to check", "Continue driving to the nearest workshop", "Pour water on the engine"],
    options_ms: ["Berhenti dengan selamat, matikan enjin, evakuasi semua penumpang, hubungi perkhidmatan kecemasan", "Buka bonet serta-merta untuk memeriksa", "Teruskan memandu ke bengkel terdekat", "Tuangkan air pada enjin"],
    correct_index: 0,
    explanation_en: "If the engine catches fire: pull over safely away from traffic, turn off the engine, evacuate all passengers immediately, and call emergency services (999). Do not open the bonnet.",
    explanation_ms: "Jika enjin terbakar: berhenti dengan selamat jauh dari trafik, matikan enjin, evakuasi semua penumpang serta-merta, dan hubungi perkhidmatan kecemasan (999). Jangan buka bonet.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 59,
    question_en: "What is the recommended tyre tread depth minimum in Malaysia?",
    question_ms: "Apakah kedalaman alur tayar minimum yang disyorkan di Malaysia?",
    options_en: ["1.6 mm", "3 mm", "5 mm", "0.5 mm"],
    options_ms: ["1.6 mm", "3 mm", "5 mm", "0.5 mm"],
    correct_index: 0,
    explanation_en: "The minimum legal tyre tread depth in Malaysia is 1.6 mm. Below this, the tyre must be replaced as it significantly reduces wet-road grip.",
    explanation_ms: "Kedalaman alur tayar minimum yang sah di Malaysia ialah 1.6 mm. Di bawah ini, tayar mesti diganti kerana ia mengurangkan cengkaman jalan basah dengan ketara.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "quiz-pool",
    order_index: 60,
    question_en: "What is the emergency telephone number in Malaysia?",
    question_ms: "Apakah nombor telefon kecemasan di Malaysia?",
    options_en: ["999", "911", "112", "000"],
    options_ms: ["999", "911", "112", "000"],
    correct_index: 0,
    explanation_en: "The emergency telephone number in Malaysia is 999. It connects to police, fire brigade, and ambulance services. 112 also works on mobile phones.",
    explanation_ms: "Nombor telefon kecemasan di Malaysia ialah 999. Ia menghubungkan kepada polis, bomba, dan perkhidmatan ambulans. 112 juga berfungsi pada telefon bimbit.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
];

// ---------------------------------------------------------------------------
// MOCK SET 1 — 50 questions
// ---------------------------------------------------------------------------
export const MOCK_1 = [
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 1,
    question_en: "What does a red triangular sign with a picture of a deer mean?",
    question_ms: "Apakah maksud tanda segitiga merah dengan gambar rusa?",
    options_en: ["Wild animals may cross the road", "Deer farm ahead", "No animals allowed", "Animal sanctuary zone"],
    options_ms: ["Haiwan liar mungkin melintas jalan", "Ladang rusa di hadapan", "Tiada haiwan dibenarkan", "Zon perlindungan haiwan"],
    correct_index: 0,
    explanation_en: "A triangular warning sign with a deer warns drivers that wild animals may cross the road in that area. Reduce speed and be alert.",
    explanation_ms: "Tanda amaran segitiga dengan rusa memberi amaran kepada pemandu bahawa haiwan liar mungkin melintas jalan di kawasan itu. Kurangkan laju dan berwaspada.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 2,
    question_en: "You are driving at 80 km/h. What is the minimum safe following distance?",
    question_ms: "Anda memandu pada 80 km/j. Apakah jarak mengekori selamat minimum?",
    options_en: ["At least 2 seconds (approximately 44 metres)", "1 car length", "5 metres", "10 metres"],
    options_ms: ["Sekurang-kurangnya 2 saat (lebih kurang 44 meter)", "1 panjang kereta", "5 meter", "10 meter"],
    correct_index: 0,
    explanation_en: "At 80 km/h, the 2-second rule gives approximately 44 metres of following distance. In wet conditions, double this to 4 seconds.",
    explanation_ms: "Pada 80 km/j, peraturan 2 saat memberikan lebih kurang 44 meter jarak mengekori. Dalam keadaan basah, gandakan ini kepada 4 saat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "mock-1",
    order_index: 3,
    question_en: "What is the first thing you should do when you get into a car before driving?",
    question_ms: "Apakah perkara pertama yang perlu anda lakukan apabila masuk ke dalam kereta sebelum memandu?",
    options_en: ["Adjust seat, mirrors, and fasten seatbelt", "Start the engine", "Check the fuel gauge", "Turn on the radio"],
    options_ms: ["Laraskan tempat duduk, cermin, dan pasang tali pinggang keledar", "Hidupkan enjin", "Periksa tolok bahan api", "Hidupkan radio"],
    correct_index: 0,
    explanation_en: "Before driving, always adjust your seat position, adjust all mirrors for maximum visibility, and fasten your seatbelt before starting the engine.",
    explanation_ms: "Sebelum memandu, sentiasa laraskan kedudukan tempat duduk anda, laraskan semua cermin untuk penglihatan maksimum, dan pasang tali pinggang keledar sebelum menghidupkan enjin.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 4,
    question_en: "A sign showing a bridge with weight limit '5T' means:",
    question_ms: "Tanda yang menunjukkan jambatan dengan had berat '5T' bermaksud:",
    options_en: ["Vehicles over 5 tonnes are prohibited from crossing", "Bridge can hold 5 tonnes maximum total", "Speed limit of 5 km/h on bridge", "5 tonne trucks only"],
    options_ms: ["Kenderaan melebihi 5 tan dilarang melintas", "Jambatan boleh menampung maksimum 5 tan jumlah", "Had laju 5 km/j di jambatan", "Trak 5 tan sahaja"],
    correct_index: 0,
    explanation_en: "A weight limit sign on a bridge means vehicles exceeding that weight (in tonnes) are prohibited from crossing to protect the bridge structure.",
    explanation_ms: "Tanda had berat di jambatan bermaksud kenderaan yang melebihi berat tersebut (dalam tan) dilarang melintas untuk melindungi struktur jambatan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 5,
    question_en: "When is it permissible to drive in the right lane on a Malaysian highway?",
    question_ms: "Bilakah dibenarkan memandu di lorong kanan di lebuh raya Malaysia?",
    options_en: ["Only when overtaking — return to left lane after", "At all times if you are driving fast", "When the left lane is congested", "Only for motorcycles"],
    options_ms: ["Hanya semasa memotong — kembali ke lorong kiri selepas itu", "Pada setiap masa jika anda memandu laju", "Apabila lorong kiri sesak", "Hanya untuk motosikal"],
    correct_index: 0,
    explanation_en: "The right lane on a highway is for overtaking only. After overtaking, drivers must return to the left lane. Hogging the right lane is an offence.",
    explanation_ms: "Lorong kanan di lebuh raya adalah untuk memotong sahaja. Selepas memotong, pemandu mesti kembali ke lorong kiri. Menduduki lorong kanan adalah satu kesalahan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "mock-1",
    order_index: 6,
    question_en: "What does ABS (Anti-lock Braking System) do?",
    question_ms: "Apakah fungsi ABS (Sistem Brek Anti-kunci)?",
    options_en: ["Prevents wheels from locking up during hard braking, maintaining steering control", "Automatically applies brakes when danger is detected", "Reduces brake pad wear", "Increases braking distance"],
    options_ms: ["Mencegah roda daripada terkunci semasa brek keras, mengekalkan kawalan stereng", "Secara automatik menggunakan brek apabila bahaya dikesan", "Mengurangkan kehausan pad brek", "Meningkatkan jarak brek"],
    correct_index: 0,
    explanation_en: "ABS prevents wheel lock-up during emergency braking, allowing the driver to maintain steering control and potentially steer around an obstacle while braking.",
    explanation_ms: "ABS mencegah roda terkunci semasa brek kecemasan, membolehkan pemandu mengekalkan kawalan stereng dan berpotensi mengelak halangan semasa brek.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 7,
    question_en: "What does a sign with a red circle and a bicycle inside mean?",
    question_ms: "Apakah maksud tanda dengan bulatan merah dan basikal di dalamnya?",
    options_en: ["No bicycles allowed", "Bicycle lane ahead", "Bicycle parking", "Bicycle crossing"],
    options_ms: ["Tiada basikal dibenarkan", "Lorong basikal di hadapan", "Tempat letak basikal", "Lintasan basikal"],
    correct_index: 0,
    explanation_en: "A red circle with a bicycle symbol is a prohibition sign meaning bicycles are not allowed on that road or area.",
    explanation_ms: "Bulatan merah dengan simbol basikal ialah tanda larangan yang bermaksud basikal tidak dibenarkan di jalan atau kawasan tersebut.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 8,
    question_en: "What should you do when approaching a roundabout?",
    question_ms: "Apakah yang perlu anda lakukan apabila menghampiri bulatan?",
    options_en: ["Give way to traffic already in the roundabout", "You have right of way as you are entering", "Sound your horn before entering", "Accelerate to merge with traffic"],
    options_ms: ["Beri laluan kepada trafik yang sudah berada dalam bulatan", "Anda mempunyai keutamaan laluan kerana anda memasuki", "Bunyikan hon sebelum memasuki", "Pecutkan untuk bergabung dengan trafik"],
    correct_index: 0,
    explanation_en: "At a roundabout, vehicles already circulating inside have right of way. Entering vehicles must give way and only enter when there is a safe gap.",
    explanation_ms: "Di bulatan, kenderaan yang sudah beredar di dalam mempunyai keutamaan laluan. Kenderaan yang memasuki mesti memberi laluan dan hanya masuk apabila ada jurang yang selamat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "mock-1",
    order_index: 9,
    question_en: "What is the effect of overloading a vehicle?",
    question_ms: "Apakah kesan memuat lebih kenderaan?",
    options_en: ["Longer braking distance, poor handling, tyre damage, and increased accident risk", "Better stability due to lower centre of gravity", "Improved fuel economy", "No significant effect"],
    options_ms: ["Jarak brek lebih panjang, pengendalian buruk, kerosakan tayar, dan peningkatan risiko kemalangan", "Kestabilan lebih baik kerana pusat graviti lebih rendah", "Ekonomi bahan api lebih baik", "Tiada kesan ketara"],
    correct_index: 0,
    explanation_en: "Overloading increases braking distance, causes poor vehicle handling, damages tyres and suspension, and significantly increases the risk of accidents.",
    explanation_ms: "Memuat lebih meningkatkan jarak brek, menyebabkan pengendalian kenderaan yang buruk, merosakkan tayar dan suspensi, dan meningkatkan risiko kemalangan dengan ketara.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 10,
    question_en: "A sign showing a road splitting into two arrows indicates:",
    question_ms: "Tanda yang menunjukkan jalan bercabang kepada dua anak panah menunjukkan:",
    options_en: ["Road forks ahead — keep left or right as directed", "Overtaking lane begins", "Two-way traffic starts", "Road merges ahead"],
    options_ms: ["Jalan bercabang di hadapan — ikut kiri atau kanan seperti yang diarahkan", "Lorong memotong bermula", "Trafik dua hala bermula", "Jalan bergabung di hadapan"],
    correct_index: 0,
    explanation_en: "A road fork sign warns that the road ahead splits into two directions. Drivers should follow directional signs to take the correct route.",
    explanation_ms: "Tanda jalan bercabang memberi amaran bahawa jalan di hadapan berpecah kepada dua arah. Pemandu harus mengikuti tanda arah untuk mengambil laluan yang betul.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 11,
    question_en: "What is the speed limit in a built-up area (town/city) in Malaysia?",
    question_ms: "Apakah had laju di kawasan pembangunan (bandar/kota) di Malaysia?",
    options_en: ["50 km/h", "60 km/h", "70 km/h", "40 km/h"],
    options_ms: ["50 km/j", "60 km/j", "70 km/j", "40 km/j"],
    correct_index: 0,
    explanation_en: "The default speed limit in built-up areas (towns and cities) in Malaysia is 50 km/h unless otherwise indicated by signs.",
    explanation_ms: "Had laju lalai di kawasan pembangunan (bandar dan kota) di Malaysia ialah 50 km/j melainkan dinyatakan sebaliknya oleh tanda.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "mock-1",
    order_index: 12,
    question_en: "What should you do if a tyre blows out at high speed?",
    question_ms: "Apakah yang perlu anda lakukan jika tayar meletup pada laju tinggi?",
    options_en: ["Hold the steering firmly, ease off accelerator, brake gently, steer to safety", "Brake hard immediately", "Accelerate to maintain control", "Turn the steering wheel sharply"],
    options_ms: ["Pegang stereng dengan kuat, kurangkan pemecut, brek perlahan, stereng ke tempat selamat", "Brek keras serta-merta", "Pecutkan untuk mengekalkan kawalan", "Pusingkan stereng dengan tajam"],
    correct_index: 0,
    explanation_en: "During a tyre blowout: grip the steering wheel firmly, ease off the accelerator gradually, brake gently (do not slam brakes), and steer to a safe stop.",
    explanation_ms: "Semasa tayar meletup: pegang stereng dengan kuat, kurangkan pemecut secara beransur, brek perlahan (jangan hentam brek), dan stereng ke berhenti yang selamat.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 13,
    question_en: "What does a sign with a red circle and a horn symbol crossed out mean?",
    question_ms: "Apakah maksud tanda dengan bulatan merah dan simbol hon dipalang?",
    options_en: ["No sounding of horn", "Horn must be used", "Quiet zone ahead", "No loud music"],
    options_ms: ["Dilarang membunyikan hon", "Hon mesti digunakan", "Zon sunyi di hadapan", "Tiada muzik kuat"],
    correct_index: 0,
    explanation_en: "A crossed-out horn symbol in a red circle means sounding the horn is prohibited in that area, typically near hospitals or quiet residential zones.",
    explanation_ms: "Simbol hon dipalang dalam bulatan merah bermaksud membunyikan hon dilarang di kawasan tersebut, biasanya berhampiran hospital atau zon kediaman sunyi.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 14,
    question_en: "What does a broken white line in the centre of the road mean?",
    question_ms: "Apakah maksud garisan putih putus-putus di tengah jalan?",
    options_en: ["Overtaking is permitted when safe to do so", "No overtaking at all", "Lane boundary only — no crossing", "Pedestrian crossing zone"],
    options_ms: ["Memotong dibenarkan apabila selamat berbuat demikian", "Tiada memotong langsung", "Sempadan lorong sahaja — tiada melintas", "Zon lintasan pejalan kaki"],
    correct_index: 0,
    explanation_en: "A broken white centre line means overtaking is permitted when it is safe to do so and the road ahead is clear.",
    explanation_ms: "Garisan putih putus-putus di tengah bermaksud memotong dibenarkan apabila selamat berbuat demikian dan jalan di hadapan kosong.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "mock-1",
    order_index: 15,
    question_en: "What is the purpose of hazard warning lights?",
    question_ms: "Apakah tujuan lampu amaran bahaya?",
    options_en: ["To warn other road users of a hazard or emergency stop", "To signal a right turn", "To indicate the vehicle is parked legally", "To replace headlights in fog"],
    options_ms: ["Untuk memberi amaran kepada pengguna jalan lain tentang bahaya atau berhenti kecemasan", "Untuk memberi isyarat belok kanan", "Untuk menunjukkan kenderaan diletakkan secara sah", "Untuk menggantikan lampu hadapan dalam kabus"],
    correct_index: 0,
    explanation_en: "Hazard warning lights (all four indicators flashing) warn other road users of a hazard, breakdown, or emergency stop. They should not be used while driving normally.",
    explanation_ms: "Lampu amaran bahaya (semua empat penunjuk berkelip) memberi amaran kepada pengguna jalan lain tentang bahaya, kerosakan, atau berhenti kecemasan. Ia tidak boleh digunakan semasa memandu secara normal.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 16,
    question_en: "A sign showing a car with lines beneath it (like vibration) warns of:",
    question_ms: "Tanda yang menunjukkan kereta dengan garisan di bawahnya (seperti getaran) memberi amaran tentang:",
    options_en: ["Rumble strips or uneven road surface ahead", "Earthquake zone", "Speed camera ahead", "Road works with vibration"],
    options_ms: ["Jalur getaran atau permukaan jalan tidak rata di hadapan", "Zon gempa bumi", "Kamera laju di hadapan", "Kerja jalan dengan getaran"],
    correct_index: 0,
    explanation_en: "This sign warns of rumble strips or an uneven road surface ahead. Drivers should reduce speed to avoid losing control.",
    explanation_ms: "Tanda ini memberi amaran tentang jalur getaran atau permukaan jalan tidak rata di hadapan. Pemandu harus mengurangkan laju untuk mengelak kehilangan kawalan.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 17,
    question_en: "When must you use your rear fog lights?",
    question_ms: "Bilakah anda mesti menggunakan lampu kabus belakang?",
    options_en: ["When visibility is reduced to less than 100 metres due to fog, smoke, or heavy rain", "Every time it rains", "Only in tunnels", "At night on unlit roads"],
    options_ms: ["Apabila penglihatan berkurangan kepada kurang daripada 100 meter akibat kabus, asap, atau hujan lebat", "Setiap kali hujan", "Hanya dalam terowong", "Pada waktu malam di jalan tanpa lampu"],
    correct_index: 0,
    explanation_en: "Rear fog lights should be used when visibility drops below 100 metres due to fog, heavy rain, or smoke. Turn them off when visibility improves.",
    explanation_ms: "Lampu kabus belakang harus digunakan apabila penglihatan turun di bawah 100 meter akibat kabus, hujan lebat, atau asap. Matikannya apabila penglihatan bertambah baik.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "safety-principles",
    set_id: "mock-1",
    order_index: 18,
    question_en: "What is the correct hand position on the steering wheel?",
    question_ms: "Apakah kedudukan tangan yang betul pada stereng?",
    options_en: ["9 o'clock and 3 o'clock (or 8 and 4)", "12 o'clock and 6 o'clock", "10 o'clock and 2 o'clock (traditional)", "One hand at 12 o'clock"],
    options_ms: ["Pukul 9 dan pukul 3 (atau 8 dan 4)", "Pukul 12 dan pukul 6", "Pukul 10 dan pukul 2 (tradisional)", "Satu tangan pada pukul 12"],
    correct_index: 0,
    explanation_en: "Modern driving instruction recommends the 9 and 3 position (or 8 and 4) for better control and safety with airbag-equipped vehicles.",
    explanation_ms: "Pengajaran memandu moden mengesyorkan kedudukan 9 dan 3 (atau 8 dan 4) untuk kawalan dan keselamatan yang lebih baik dengan kenderaan bersenjata beg udara.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "road-signs",
    set_id: "mock-1",
    order_index: 19,
    question_en: "What does a blue rectangular sign with a white 'H' indicate?",
    question_ms: "Apakah maksud tanda segi empat tepat biru dengan 'H' putih?",
    options_en: ["Hospital ahead", "Hotel ahead", "Helipad nearby", "Highway entrance"],
    options_ms: ["Hospital di hadapan", "Hotel di hadapan", "Helipad berdekatan", "Masuk lebuh raya"],
    correct_index: 0,
    explanation_en: "A blue sign with a white 'H' indicates a hospital ahead. Drivers should be aware of ambulances and reduce speed near hospital zones.",
    explanation_ms: "Tanda biru dengan 'H' putih menunjukkan hospital di hadapan. Pemandu harus berwaspada terhadap ambulans dan mengurangkan laju berhampiran zon hospital.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
  {
    category: "traffic-rules",
    set_id: "mock-1",
    order_index: 20,
    question_en: "What is the penalty for not wearing a seatbelt in Malaysia?",
    question_ms: "Apakah hukuman kerana tidak memakai tali pinggang keledar di Malaysia?",
    options_en: ["Fine and demerit points under the Road Transport Act", "Verbal warning only", "Vehicle impoundment", "Licence suspension immediately"],
    options_ms: ["Denda dan mata demerit di bawah Akta Pengangkutan Jalan", "Amaran lisan sahaja", "Kenderaan dirampas", "Penggantungan lesen serta-merta"],
    correct_index: 0,
    explanation_en: "Not wearing a seatbelt in Malaysia is an offence under the Road Transport Act, punishable by a fine and demerit points on your driving licence.",
    explanation_ms: "Tidak memakai tali pinggang keledar di Malaysia adalah kesalahan di bawah Akta Pengangkutan Jalan, boleh dihukum dengan denda dan mata demerit pada lesen memandu anda.",
    image_url: null,
    source_url: "https://www.jpj.gov.my",
  },
];
